package kma.databases.validators.fields;

public enum FieldValidatorKey {
    NAME_SURNAME, PATRONYMIC, CURRENCY, DATE_OF_BIRTH, PHONE, CITY, STREET, ZIP_CODE, OPTIONAL_CITY,
    OPTIONAL_STREET, OPTIONAL_ZIP_CODE, PERCENT, DATE, NUMBER, PRODUCT_CATEGORY_NAME, CHARACTERISTICS, PASSWORD,
    PROMOTIONAL, NUMERIC_ID, STRING_ID, HASH_PASSWORD
}
