package kma.databases.validators.fields;

public enum FieldValidatorKey {
    NAME_SURNAME, PATRONYMIC, CURRENCY, DATE_OF_BIRTH, DATE_OF_START, PHONE, CITY, STREET, ZIP_CODE, OPTIONAL_CITY,
    OPTIONAL_STREET, OPTIONAL_ZIP_CODE, PERCENT, PRINT_DATE, NUMBER, PRODUCT_CATEGORY_NAME, CHARACTERISTICS, PASSWORD,
    PROMOTIONAL, NUMERIC_ID, STRING_ID
}
